/* eslint-disable indent */
// This file is generated by Slice Machine. Update with care!

import TextImageRight from './TextImageRight'

export { TextImageRight }

export const components = {
  text_image_right: TextImageRight
}
